### ISSUE TITLE
Latest patch and TTT updates seem to cause problems with loading games with this mod

### ISSUE THREAD

**Issue by SimpleFish5655** [madisoncfallin/MadisonsMetagaming#1]
The latest patch 2.02c and Vek's updates to TTT seem to cause slow load times with this mod enabled (for both fresh characters and existing savegames).

I get a bunch of repeating errors from the GameLog.
[Error.txt](https://github.com/madisoncfallin/MadisonsMetagaming/files/9838599/Error.txt)

Disabling this mod resolves the slow loading times.

**Comment by madisoncfallin** [comment]
Resolved this with the latest update. Thanks for reporting it! 😄
